CREATE TABLE IF NOT EXISTS legend_information (
    id SERIAL PRIMARY KEY,
    heading TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);